/*

Don't alter this file, it was generated.

*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "code.cloudfoundry.org/cf-operator/pkg/kube/apis/extendedjob/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExtendedJobs implements ExtendedJobInterface
type FakeExtendedJobs struct {
	Fake *FakeExtendedjobV1alpha1
	ns   string
}

var extendedjobsResource = schema.GroupVersionResource{Group: "extendedjob", Version: "v1alpha1", Resource: "extendedjobs"}

var extendedjobsKind = schema.GroupVersionKind{Group: "extendedjob", Version: "v1alpha1", Kind: "ExtendedJob"}

// Get takes name of the extendedJob, and returns the corresponding extendedJob object, and an error if there is any.
func (c *FakeExtendedJobs) Get(name string, options v1.GetOptions) (result *v1alpha1.ExtendedJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(extendedjobsResource, c.ns, name), &v1alpha1.ExtendedJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendedJob), err
}

// List takes label and field selectors, and returns the list of ExtendedJobs that match those selectors.
func (c *FakeExtendedJobs) List(opts v1.ListOptions) (result *v1alpha1.ExtendedJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(extendedjobsResource, extendedjobsKind, c.ns, opts), &v1alpha1.ExtendedJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ExtendedJobList{ListMeta: obj.(*v1alpha1.ExtendedJobList).ListMeta}
	for _, item := range obj.(*v1alpha1.ExtendedJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested extendedJobs.
func (c *FakeExtendedJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(extendedjobsResource, c.ns, opts))

}

// Create takes the representation of a extendedJob and creates it.  Returns the server's representation of the extendedJob, and an error, if there is any.
func (c *FakeExtendedJobs) Create(extendedJob *v1alpha1.ExtendedJob) (result *v1alpha1.ExtendedJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(extendedjobsResource, c.ns, extendedJob), &v1alpha1.ExtendedJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendedJob), err
}

// Update takes the representation of a extendedJob and updates it. Returns the server's representation of the extendedJob, and an error, if there is any.
func (c *FakeExtendedJobs) Update(extendedJob *v1alpha1.ExtendedJob) (result *v1alpha1.ExtendedJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(extendedjobsResource, c.ns, extendedJob), &v1alpha1.ExtendedJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendedJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeExtendedJobs) UpdateStatus(extendedJob *v1alpha1.ExtendedJob) (*v1alpha1.ExtendedJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(extendedjobsResource, "status", c.ns, extendedJob), &v1alpha1.ExtendedJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendedJob), err
}

// Delete takes name of the extendedJob and deletes it. Returns an error if one occurs.
func (c *FakeExtendedJobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(extendedjobsResource, c.ns, name), &v1alpha1.ExtendedJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExtendedJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(extendedjobsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ExtendedJobList{})
	return err
}

// Patch applies the patch and returns the patched extendedJob.
func (c *FakeExtendedJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ExtendedJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(extendedjobsResource, c.ns, name, data, subresources...), &v1alpha1.ExtendedJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendedJob), err
}
