/*

Don't alter this file, it was generated.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// QuarksStatefulSetListerExpansion allows custom methods to be added to
// QuarksStatefulSetLister.
type QuarksStatefulSetListerExpansion interface{}

// QuarksStatefulSetNamespaceListerExpansion allows custom methods to be added to
// QuarksStatefulSetNamespaceLister.
type QuarksStatefulSetNamespaceListerExpansion interface{}
