/*

Don't alter this file, it was generated.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// QuarksSecretListerExpansion allows custom methods to be added to
// QuarksSecretLister.
type QuarksSecretListerExpansion interface{}

// QuarksSecretNamespaceListerExpansion allows custom methods to be added to
// QuarksSecretNamespaceLister.
type QuarksSecretNamespaceListerExpansion interface{}
