/*

Don't alter this file, it was generated.

*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "code.cloudfoundry.org/cf-operator/pkg/kube/apis/extendedsecret/v1alpha1"
	scheme "code.cloudfoundry.org/cf-operator/pkg/kube/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ExtendedSecretsGetter has a method to return a ExtendedSecretInterface.
// A group's client should implement this interface.
type ExtendedSecretsGetter interface {
	ExtendedSecrets(namespace string) ExtendedSecretInterface
}

// ExtendedSecretInterface has methods to work with ExtendedSecret resources.
type ExtendedSecretInterface interface {
	Create(*v1alpha1.ExtendedSecret) (*v1alpha1.ExtendedSecret, error)
	Update(*v1alpha1.ExtendedSecret) (*v1alpha1.ExtendedSecret, error)
	UpdateStatus(*v1alpha1.ExtendedSecret) (*v1alpha1.ExtendedSecret, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ExtendedSecret, error)
	List(opts v1.ListOptions) (*v1alpha1.ExtendedSecretList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ExtendedSecret, err error)
	ExtendedSecretExpansion
}

// extendedSecrets implements ExtendedSecretInterface
type extendedSecrets struct {
	client rest.Interface
	ns     string
}

// newExtendedSecrets returns a ExtendedSecrets
func newExtendedSecrets(c *ExtendedsecretV1alpha1Client, namespace string) *extendedSecrets {
	return &extendedSecrets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the extendedSecret, and returns the corresponding extendedSecret object, and an error if there is any.
func (c *extendedSecrets) Get(name string, options v1.GetOptions) (result *v1alpha1.ExtendedSecret, err error) {
	result = &v1alpha1.ExtendedSecret{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("extendedsecrets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ExtendedSecrets that match those selectors.
func (c *extendedSecrets) List(opts v1.ListOptions) (result *v1alpha1.ExtendedSecretList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ExtendedSecretList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("extendedsecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested extendedSecrets.
func (c *extendedSecrets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("extendedsecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a extendedSecret and creates it.  Returns the server's representation of the extendedSecret, and an error, if there is any.
func (c *extendedSecrets) Create(extendedSecret *v1alpha1.ExtendedSecret) (result *v1alpha1.ExtendedSecret, err error) {
	result = &v1alpha1.ExtendedSecret{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("extendedsecrets").
		Body(extendedSecret).
		Do().
		Into(result)
	return
}

// Update takes the representation of a extendedSecret and updates it. Returns the server's representation of the extendedSecret, and an error, if there is any.
func (c *extendedSecrets) Update(extendedSecret *v1alpha1.ExtendedSecret) (result *v1alpha1.ExtendedSecret, err error) {
	result = &v1alpha1.ExtendedSecret{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("extendedsecrets").
		Name(extendedSecret.Name).
		Body(extendedSecret).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *extendedSecrets) UpdateStatus(extendedSecret *v1alpha1.ExtendedSecret) (result *v1alpha1.ExtendedSecret, err error) {
	result = &v1alpha1.ExtendedSecret{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("extendedsecrets").
		Name(extendedSecret.Name).
		SubResource("status").
		Body(extendedSecret).
		Do().
		Into(result)
	return
}

// Delete takes name of the extendedSecret and deletes it. Returns an error if one occurs.
func (c *extendedSecrets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("extendedsecrets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *extendedSecrets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("extendedsecrets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched extendedSecret.
func (c *extendedSecrets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ExtendedSecret, err error) {
	result = &v1alpha1.ExtendedSecret{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("extendedsecrets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
