/*

Don't alter this file, it was generated.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BOSHDeploymentListerExpansion allows custom methods to be added to
// BOSHDeploymentLister.
type BOSHDeploymentListerExpansion interface{}

// BOSHDeploymentNamespaceListerExpansion allows custom methods to be added to
// BOSHDeploymentNamespaceLister.
type BOSHDeploymentNamespaceListerExpansion interface{}
