/*

Don't alter this file, it was generated.

*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "code.cloudfoundry.org/cf-operator/pkg/kube/apis/quarkssecret/v1alpha1"
	scheme "code.cloudfoundry.org/cf-operator/pkg/kube/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// QuarksSecretsGetter has a method to return a QuarksSecretInterface.
// A group's client should implement this interface.
type QuarksSecretsGetter interface {
	QuarksSecrets(namespace string) QuarksSecretInterface
}

// QuarksSecretInterface has methods to work with QuarksSecret resources.
type QuarksSecretInterface interface {
	Create(*v1alpha1.QuarksSecret) (*v1alpha1.QuarksSecret, error)
	Update(*v1alpha1.QuarksSecret) (*v1alpha1.QuarksSecret, error)
	UpdateStatus(*v1alpha1.QuarksSecret) (*v1alpha1.QuarksSecret, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.QuarksSecret, error)
	List(opts v1.ListOptions) (*v1alpha1.QuarksSecretList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.QuarksSecret, err error)
	QuarksSecretExpansion
}

// quarksSecrets implements QuarksSecretInterface
type quarksSecrets struct {
	client rest.Interface
	ns     string
}

// newQuarksSecrets returns a QuarksSecrets
func newQuarksSecrets(c *QuarkssecretV1alpha1Client, namespace string) *quarksSecrets {
	return &quarksSecrets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the quarksSecret, and returns the corresponding quarksSecret object, and an error if there is any.
func (c *quarksSecrets) Get(name string, options v1.GetOptions) (result *v1alpha1.QuarksSecret, err error) {
	result = &v1alpha1.QuarksSecret{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("quarkssecrets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of QuarksSecrets that match those selectors.
func (c *quarksSecrets) List(opts v1.ListOptions) (result *v1alpha1.QuarksSecretList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.QuarksSecretList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("quarkssecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested quarksSecrets.
func (c *quarksSecrets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("quarkssecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a quarksSecret and creates it.  Returns the server's representation of the quarksSecret, and an error, if there is any.
func (c *quarksSecrets) Create(quarksSecret *v1alpha1.QuarksSecret) (result *v1alpha1.QuarksSecret, err error) {
	result = &v1alpha1.QuarksSecret{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("quarkssecrets").
		Body(quarksSecret).
		Do().
		Into(result)
	return
}

// Update takes the representation of a quarksSecret and updates it. Returns the server's representation of the quarksSecret, and an error, if there is any.
func (c *quarksSecrets) Update(quarksSecret *v1alpha1.QuarksSecret) (result *v1alpha1.QuarksSecret, err error) {
	result = &v1alpha1.QuarksSecret{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("quarkssecrets").
		Name(quarksSecret.Name).
		Body(quarksSecret).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *quarksSecrets) UpdateStatus(quarksSecret *v1alpha1.QuarksSecret) (result *v1alpha1.QuarksSecret, err error) {
	result = &v1alpha1.QuarksSecret{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("quarkssecrets").
		Name(quarksSecret.Name).
		SubResource("status").
		Body(quarksSecret).
		Do().
		Into(result)
	return
}

// Delete takes name of the quarksSecret and deletes it. Returns an error if one occurs.
func (c *quarksSecrets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("quarkssecrets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *quarksSecrets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("quarkssecrets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched quarksSecret.
func (c *quarksSecrets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.QuarksSecret, err error) {
	result = &v1alpha1.QuarksSecret{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("quarkssecrets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
