/*

Don't alter this file, it was generated.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ExtendedSecretListerExpansion allows custom methods to be added to
// ExtendedSecretLister.
type ExtendedSecretListerExpansion interface{}

// ExtendedSecretNamespaceListerExpansion allows custom methods to be added to
// ExtendedSecretNamespaceLister.
type ExtendedSecretNamespaceListerExpansion interface{}
