kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: quarksstatefulsets.quarks.cloudfoundry.org
spec:
  group: quarks.cloudfoundry.org
  names:
    plural: quarksstatefulsets
    singular: quarksstatefulset
    shortNames:
      - qsts
    kind: QuarksStatefulSet
    listKind: QuarksStatefulSetList
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - template
              properties:
                activePassiveProbes:
                  description: >-
                    Defines probes to determine active/passive component
                    instances
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                injectReplicasEnv:
                  description: >-
                    Determines if the REPLICAS env var is injected into pod
                    containers.
                  type: boolean
                template:
                  description: A template for a regular StatefulSet
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                updateOnConfigChange:
                  description: >-
                    Indicate whether to update Pods in the StatefulSet when an
                    env value or mount changes
                  type: boolean
                zoneNodeLabel:
                  description: Indicates the node label that a node locates
                  type: string
                zones:
                  description: >-
                    Indicates the availability zones that the QuarksStatefulSet
                    needs to span
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                lastReconcile:
                  type: string
                ready:
                  type: boolean
  conversion:
    strategy: None
