kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: boshdeployments.quarks.cloudfoundry.org
spec:
  group: quarks.cloudfoundry.org
  names:
    plural: boshdeployments
    singular: boshdeployment
    shortNames:
      - bdpl
      - bdpls
    kind: BOSHDeployment
    listKind: BOSHDeploymentList
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - manifest
              properties:
                manifest:
                  type: object
                  required:
                    - type
                    - name
                  properties:
                    name:
                      type: string
                      minLength: 1
                    type:
                      type: string
                      enum:
                        - configmap
                        - secret
                        - url
                ops:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - name
                    properties:
                      name:
                        type: string
                        minLength: 1
                      type:
                        type: string
                        enum:
                          - configmap
                          - secret
                          - url
                vars:
                  type: array
                  items:
                    type: object
                    required:
                      - secret
                      - name
                    properties:
                      name:
                        type: string
                        minLength: 1
                      secret:
                        type: string
                        minLength: 1
            status:
              type: object
              properties:
                completedJobCount:
                  type: integer
                deployedInstanceGroups:
                  type: integer
                lastReconcile:
                  type: string
                  nullable: true
                message:
                  type: string
                state:
                  type: string
                stateTimestamp:
                  type: string
                  nullable: true
                totalInstanceGroups:
                  type: integer
                totalJobCount:
                  type: integer
  conversion:
    strategy: None