apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: 2020-04-30T14:32:12Z
  generation: 1
  name: quarkssecrets.quarks.cloudfoundry.org
  resourceVersion: "2512195"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/quarkssecrets.quarks.cloudfoundry.org
  uid: 39429135-ac0b-4a3c-9361-9aff628226e0
spec:
  conversion:
    strategy: None
  group: quarks.cloudfoundry.org
  names:
    kind: QuarksSecret
    listKind: QuarksSecretList
    plural: quarkssecrets
    shortNames:
    - qsec
    - qsecs
    singular: quarkssecret
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            copies:
              description: A list of namespaced names where to copy generated secrets
              items:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              type: array
            request:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            secretName:
              description: The name of the generated secret
              minLength: 1
              type: string
            type:
              description: 'What kind of secret to generate: password, certificate,
                ssh, rsa'
              minLength: 1
              type: string
          required:
          - secretName
          - type
          type: object
        status:
          properties:
            generated:
              type: boolean
            lastReconcile:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: QuarksSecret
    listKind: QuarksSecretList
    plural: quarkssecrets
    shortNames:
    - qsec
    - qsecs
    singular: quarkssecret
  conditions:
  - lastTransitionTime: 2020-04-30T14:32:12Z
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
