---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: boshdeployments.quarks.cloudfoundry.org
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: quarks.cloudfoundry.org
  names:
    kind: BOSHDeployment
    listKind: BOSHDeploymentList
    plural: boshdeployments
    singular: boshdeployment
    shortNames:
        - bdpl
        - bdpls
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          required: [manifest]
          properties:
            manifest:
              type: object
              required: [type, name]
              properties:
                type:
                  type: string
                  enum: ["configmap", "secret", "url"]
                name:
                  type: string
                  minLength: 1
            ops:
              type: array
              items:
                type: object
                required: [type, name]
                properties:
                  type:
                    type: string
                    enum: ["configmap", "secret", "url"]
                  name:
                    type: string
                    minLength: 1
