---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: quarkssecrets.quarks.cloudfoundry.org
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: quarks.cloudfoundry.org
  names:
    kind: QuarksSecret
    listKind: QuarksSecretList
    plural: quarkssecrets
    singular: quarkssecret
    shortNames:
        - qsec
        - qsecs
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
