apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: boshdeployments.quarks.cloudfoundry.org
spec:
  conversion:
    strategy: None
  group: quarks.cloudfoundry.org
  names:
    kind: BOSHDeployment
    listKind: BOSHDeploymentList
    plural: boshdeployments
    shortNames:
    - bdpl
    - bdpls
    singular: boshdeployment
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            manifest:
              properties:
                name:
                  minLength: 1
                  type: string
                type:
                  enum:
                  - configmap
                  - secret
                  - url
                  type: string
              required:
              - type
              - name
              type: object
            ops:
              items:
                properties:
                  name:
                    minLength: 1
                    type: string
                  type:
                    enum:
                    - configmap
                    - secret
                    - url
                    type: string
                required:
                - type
                - name
                type: object
              type: array
          required:
          - manifest
          type: object
        status:
          properties:
            lastReconcile:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
