/*

Don't alter this file, it was generated.

*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "code.cloudfoundry.org/cf-operator/pkg/kube/apis/extendedstatefulset/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExtendedStatefulSets implements ExtendedStatefulSetInterface
type FakeExtendedStatefulSets struct {
	Fake *FakeExtendedstatefulsetV1alpha1
	ns   string
}

var extendedstatefulsetsResource = schema.GroupVersionResource{Group: "extendedstatefulset", Version: "v1alpha1", Resource: "extendedstatefulsets"}

var extendedstatefulsetsKind = schema.GroupVersionKind{Group: "extendedstatefulset", Version: "v1alpha1", Kind: "ExtendedStatefulSet"}

// Get takes name of the extendedStatefulSet, and returns the corresponding extendedStatefulSet object, and an error if there is any.
func (c *FakeExtendedStatefulSets) Get(name string, options v1.GetOptions) (result *v1alpha1.ExtendedStatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(extendedstatefulsetsResource, c.ns, name), &v1alpha1.ExtendedStatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendedStatefulSet), err
}

// List takes label and field selectors, and returns the list of ExtendedStatefulSets that match those selectors.
func (c *FakeExtendedStatefulSets) List(opts v1.ListOptions) (result *v1alpha1.ExtendedStatefulSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(extendedstatefulsetsResource, extendedstatefulsetsKind, c.ns, opts), &v1alpha1.ExtendedStatefulSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ExtendedStatefulSetList{ListMeta: obj.(*v1alpha1.ExtendedStatefulSetList).ListMeta}
	for _, item := range obj.(*v1alpha1.ExtendedStatefulSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested extendedStatefulSets.
func (c *FakeExtendedStatefulSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(extendedstatefulsetsResource, c.ns, opts))

}

// Create takes the representation of a extendedStatefulSet and creates it.  Returns the server's representation of the extendedStatefulSet, and an error, if there is any.
func (c *FakeExtendedStatefulSets) Create(extendedStatefulSet *v1alpha1.ExtendedStatefulSet) (result *v1alpha1.ExtendedStatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(extendedstatefulsetsResource, c.ns, extendedStatefulSet), &v1alpha1.ExtendedStatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendedStatefulSet), err
}

// Update takes the representation of a extendedStatefulSet and updates it. Returns the server's representation of the extendedStatefulSet, and an error, if there is any.
func (c *FakeExtendedStatefulSets) Update(extendedStatefulSet *v1alpha1.ExtendedStatefulSet) (result *v1alpha1.ExtendedStatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(extendedstatefulsetsResource, c.ns, extendedStatefulSet), &v1alpha1.ExtendedStatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendedStatefulSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeExtendedStatefulSets) UpdateStatus(extendedStatefulSet *v1alpha1.ExtendedStatefulSet) (*v1alpha1.ExtendedStatefulSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(extendedstatefulsetsResource, "status", c.ns, extendedStatefulSet), &v1alpha1.ExtendedStatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendedStatefulSet), err
}

// Delete takes name of the extendedStatefulSet and deletes it. Returns an error if one occurs.
func (c *FakeExtendedStatefulSets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(extendedstatefulsetsResource, c.ns, name), &v1alpha1.ExtendedStatefulSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExtendedStatefulSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(extendedstatefulsetsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ExtendedStatefulSetList{})
	return err
}

// Patch applies the patch and returns the patched extendedStatefulSet.
func (c *FakeExtendedStatefulSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ExtendedStatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(extendedstatefulsetsResource, c.ns, name, data, subresources...), &v1alpha1.ExtendedStatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendedStatefulSet), err
}
