/*

Don't alter this file, it was generated.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ExtendedStatefulSetListerExpansion allows custom methods to be added to
// ExtendedStatefulSetLister.
type ExtendedStatefulSetListerExpansion interface{}

// ExtendedStatefulSetNamespaceListerExpansion allows custom methods to be added to
// ExtendedStatefulSetNamespaceLister.
type ExtendedStatefulSetNamespaceListerExpansion interface{}
