/*

Don't alter this file, it was generated.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ExtendedJobListerExpansion allows custom methods to be added to
// ExtendedJobLister.
type ExtendedJobListerExpansion interface{}

// ExtendedJobNamespaceListerExpansion allows custom methods to be added to
// ExtendedJobNamespaceLister.
type ExtendedJobNamespaceListerExpansion interface{}
