/*

Don't alter this file, it was generated.

*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "code.cloudfoundry.org/cf-operator/pkg/kube/apis/quarksstatefulset/v1alpha1"
	scheme "code.cloudfoundry.org/cf-operator/pkg/kube/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// QuarksStatefulSetsGetter has a method to return a QuarksStatefulSetInterface.
// A group's client should implement this interface.
type QuarksStatefulSetsGetter interface {
	QuarksStatefulSets(namespace string) QuarksStatefulSetInterface
}

// QuarksStatefulSetInterface has methods to work with QuarksStatefulSet resources.
type QuarksStatefulSetInterface interface {
	Create(*v1alpha1.QuarksStatefulSet) (*v1alpha1.QuarksStatefulSet, error)
	Update(*v1alpha1.QuarksStatefulSet) (*v1alpha1.QuarksStatefulSet, error)
	UpdateStatus(*v1alpha1.QuarksStatefulSet) (*v1alpha1.QuarksStatefulSet, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.QuarksStatefulSet, error)
	List(opts v1.ListOptions) (*v1alpha1.QuarksStatefulSetList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.QuarksStatefulSet, err error)
	QuarksStatefulSetExpansion
}

// quarksStatefulSets implements QuarksStatefulSetInterface
type quarksStatefulSets struct {
	client rest.Interface
	ns     string
}

// newQuarksStatefulSets returns a QuarksStatefulSets
func newQuarksStatefulSets(c *QuarksstatefulsetV1alpha1Client, namespace string) *quarksStatefulSets {
	return &quarksStatefulSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the quarksStatefulSet, and returns the corresponding quarksStatefulSet object, and an error if there is any.
func (c *quarksStatefulSets) Get(name string, options v1.GetOptions) (result *v1alpha1.QuarksStatefulSet, err error) {
	result = &v1alpha1.QuarksStatefulSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of QuarksStatefulSets that match those selectors.
func (c *quarksStatefulSets) List(opts v1.ListOptions) (result *v1alpha1.QuarksStatefulSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.QuarksStatefulSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested quarksStatefulSets.
func (c *quarksStatefulSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a quarksStatefulSet and creates it.  Returns the server's representation of the quarksStatefulSet, and an error, if there is any.
func (c *quarksStatefulSets) Create(quarksStatefulSet *v1alpha1.QuarksStatefulSet) (result *v1alpha1.QuarksStatefulSet, err error) {
	result = &v1alpha1.QuarksStatefulSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		Body(quarksStatefulSet).
		Do().
		Into(result)
	return
}

// Update takes the representation of a quarksStatefulSet and updates it. Returns the server's representation of the quarksStatefulSet, and an error, if there is any.
func (c *quarksStatefulSets) Update(quarksStatefulSet *v1alpha1.QuarksStatefulSet) (result *v1alpha1.QuarksStatefulSet, err error) {
	result = &v1alpha1.QuarksStatefulSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		Name(quarksStatefulSet.Name).
		Body(quarksStatefulSet).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *quarksStatefulSets) UpdateStatus(quarksStatefulSet *v1alpha1.QuarksStatefulSet) (result *v1alpha1.QuarksStatefulSet, err error) {
	result = &v1alpha1.QuarksStatefulSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		Name(quarksStatefulSet.Name).
		SubResource("status").
		Body(quarksStatefulSet).
		Do().
		Into(result)
	return
}

// Delete takes name of the quarksStatefulSet and deletes it. Returns an error if one occurs.
func (c *quarksStatefulSets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *quarksStatefulSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched quarksStatefulSet.
func (c *quarksStatefulSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.QuarksStatefulSet, err error) {
	result = &v1alpha1.QuarksStatefulSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
