/*

Don't alter this file, it was generated.

*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "code.cloudfoundry.org/cf-operator/pkg/kube/apis/quarksstatefulset/v1alpha1"
	scheme "code.cloudfoundry.org/cf-operator/pkg/kube/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// QuarksStatefulSetsGetter has a method to return a QuarksStatefulSetInterface.
// A group's client should implement this interface.
type QuarksStatefulSetsGetter interface {
	QuarksStatefulSets(namespace string) QuarksStatefulSetInterface
}

// QuarksStatefulSetInterface has methods to work with QuarksStatefulSet resources.
type QuarksStatefulSetInterface interface {
	Create(ctx context.Context, quarksStatefulSet *v1alpha1.QuarksStatefulSet, opts v1.CreateOptions) (*v1alpha1.QuarksStatefulSet, error)
	Update(ctx context.Context, quarksStatefulSet *v1alpha1.QuarksStatefulSet, opts v1.UpdateOptions) (*v1alpha1.QuarksStatefulSet, error)
	UpdateStatus(ctx context.Context, quarksStatefulSet *v1alpha1.QuarksStatefulSet, opts v1.UpdateOptions) (*v1alpha1.QuarksStatefulSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.QuarksStatefulSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.QuarksStatefulSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.QuarksStatefulSet, err error)
	QuarksStatefulSetExpansion
}

// quarksStatefulSets implements QuarksStatefulSetInterface
type quarksStatefulSets struct {
	client rest.Interface
	ns     string
}

// newQuarksStatefulSets returns a QuarksStatefulSets
func newQuarksStatefulSets(c *QuarksstatefulsetV1alpha1Client, namespace string) *quarksStatefulSets {
	return &quarksStatefulSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the quarksStatefulSet, and returns the corresponding quarksStatefulSet object, and an error if there is any.
func (c *quarksStatefulSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.QuarksStatefulSet, err error) {
	result = &v1alpha1.QuarksStatefulSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of QuarksStatefulSets that match those selectors.
func (c *quarksStatefulSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.QuarksStatefulSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.QuarksStatefulSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested quarksStatefulSets.
func (c *quarksStatefulSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a quarksStatefulSet and creates it.  Returns the server's representation of the quarksStatefulSet, and an error, if there is any.
func (c *quarksStatefulSets) Create(ctx context.Context, quarksStatefulSet *v1alpha1.QuarksStatefulSet, opts v1.CreateOptions) (result *v1alpha1.QuarksStatefulSet, err error) {
	result = &v1alpha1.QuarksStatefulSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(quarksStatefulSet).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a quarksStatefulSet and updates it. Returns the server's representation of the quarksStatefulSet, and an error, if there is any.
func (c *quarksStatefulSets) Update(ctx context.Context, quarksStatefulSet *v1alpha1.QuarksStatefulSet, opts v1.UpdateOptions) (result *v1alpha1.QuarksStatefulSet, err error) {
	result = &v1alpha1.QuarksStatefulSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		Name(quarksStatefulSet.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(quarksStatefulSet).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *quarksStatefulSets) UpdateStatus(ctx context.Context, quarksStatefulSet *v1alpha1.QuarksStatefulSet, opts v1.UpdateOptions) (result *v1alpha1.QuarksStatefulSet, err error) {
	result = &v1alpha1.QuarksStatefulSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		Name(quarksStatefulSet.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(quarksStatefulSet).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the quarksStatefulSet and deletes it. Returns an error if one occurs.
func (c *quarksStatefulSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *quarksStatefulSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched quarksStatefulSet.
func (c *quarksStatefulSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.QuarksStatefulSet, err error) {
	result = &v1alpha1.QuarksStatefulSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("quarksstatefulsets").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
