/*

Don't alter this file, it was generated.

*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	boshdeploymentcontrollerv1alpha1 "code.cloudfoundry.org/cf-operator/pkg/kube/apis/boshdeploymentcontroller/v1alpha1"
	versioned "code.cloudfoundry.org/cf-operator/pkg/kube/client/clientset/versioned"
	internalinterfaces "code.cloudfoundry.org/cf-operator/pkg/kube/client/informers/externalversions/internalinterfaces"
	v1alpha1 "code.cloudfoundry.org/cf-operator/pkg/kube/client/listers/boshdeploymentcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BOSHDeploymentInformer provides access to a shared informer and lister for
// BOSHDeployments.
type BOSHDeploymentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.BOSHDeploymentLister
}

type bOSHDeploymentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBOSHDeploymentInformer constructs a new informer for BOSHDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBOSHDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBOSHDeploymentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBOSHDeploymentInformer constructs a new informer for BOSHDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBOSHDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BoshdeploymentcontrollerV1alpha1().BOSHDeployments(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BoshdeploymentcontrollerV1alpha1().BOSHDeployments(namespace).Watch(options)
			},
		},
		&boshdeploymentcontrollerv1alpha1.BOSHDeployment{},
		resyncPeriod,
		indexers,
	)
}

func (f *bOSHDeploymentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBOSHDeploymentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *bOSHDeploymentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&boshdeploymentcontrollerv1alpha1.BOSHDeployment{}, f.defaultInformer)
}

func (f *bOSHDeploymentInformer) Lister() v1alpha1.BOSHDeploymentLister {
	return v1alpha1.NewBOSHDeploymentLister(f.Informer().GetIndexer())
}
