// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	context "context"
	sync "sync"

	manifest "code.cloudfoundry.org/cf-operator/pkg/bosh/manifest"
	boshdeployment "code.cloudfoundry.org/cf-operator/pkg/kube/controllers/boshdeployment"
)

type FakeDesiredManifest struct {
	ReadDesiredManifestStub        func(context.Context, string, string) (*manifest.Manifest, error)
	readDesiredManifestMutex       sync.RWMutex
	readDesiredManifestArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	readDesiredManifestReturns struct {
		result1 *manifest.Manifest
		result2 error
	}
	readDesiredManifestReturnsOnCall map[int]struct {
		result1 *manifest.Manifest
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDesiredManifest) ReadDesiredManifest(arg1 context.Context, arg2 string, arg3 string) (*manifest.Manifest, error) {
	fake.readDesiredManifestMutex.Lock()
	ret, specificReturn := fake.readDesiredManifestReturnsOnCall[len(fake.readDesiredManifestArgsForCall)]
	fake.readDesiredManifestArgsForCall = append(fake.readDesiredManifestArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	fake.recordInvocation("ReadDesiredManifest", []interface{}{arg1, arg2, arg3})
	fake.readDesiredManifestMutex.Unlock()
	if fake.ReadDesiredManifestStub != nil {
		return fake.ReadDesiredManifestStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.readDesiredManifestReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDesiredManifest) ReadDesiredManifestCallCount() int {
	fake.readDesiredManifestMutex.RLock()
	defer fake.readDesiredManifestMutex.RUnlock()
	return len(fake.readDesiredManifestArgsForCall)
}

func (fake *FakeDesiredManifest) ReadDesiredManifestCalls(stub func(context.Context, string, string) (*manifest.Manifest, error)) {
	fake.readDesiredManifestMutex.Lock()
	defer fake.readDesiredManifestMutex.Unlock()
	fake.ReadDesiredManifestStub = stub
}

func (fake *FakeDesiredManifest) ReadDesiredManifestArgsForCall(i int) (context.Context, string, string) {
	fake.readDesiredManifestMutex.RLock()
	defer fake.readDesiredManifestMutex.RUnlock()
	argsForCall := fake.readDesiredManifestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeDesiredManifest) ReadDesiredManifestReturns(result1 *manifest.Manifest, result2 error) {
	fake.readDesiredManifestMutex.Lock()
	defer fake.readDesiredManifestMutex.Unlock()
	fake.ReadDesiredManifestStub = nil
	fake.readDesiredManifestReturns = struct {
		result1 *manifest.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakeDesiredManifest) ReadDesiredManifestReturnsOnCall(i int, result1 *manifest.Manifest, result2 error) {
	fake.readDesiredManifestMutex.Lock()
	defer fake.readDesiredManifestMutex.Unlock()
	fake.ReadDesiredManifestStub = nil
	if fake.readDesiredManifestReturnsOnCall == nil {
		fake.readDesiredManifestReturnsOnCall = make(map[int]struct {
			result1 *manifest.Manifest
			result2 error
		})
	}
	fake.readDesiredManifestReturnsOnCall[i] = struct {
		result1 *manifest.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakeDesiredManifest) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.readDesiredManifestMutex.RLock()
	defer fake.readDesiredManifestMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDesiredManifest) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ boshdeployment.DesiredManifest = new(FakeDesiredManifest)
