// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	context "context"
	sync "sync"

	manifest "code.cloudfoundry.org/cf-operator/pkg/bosh/manifest"
	v1alpha1 "code.cloudfoundry.org/cf-operator/pkg/kube/apis/boshdeployment/v1alpha1"
)

type FakeResolver struct {
	ReadDesiredManifestStub        func(context.Context, string, string) (*manifest.Manifest, error)
	readDesiredManifestMutex       sync.RWMutex
	readDesiredManifestArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	readDesiredManifestReturns struct {
		result1 *manifest.Manifest
		result2 error
	}
	readDesiredManifestReturnsOnCall map[int]struct {
		result1 *manifest.Manifest
		result2 error
	}
	ResolveManifestStub        func(*v1alpha1.BOSHDeployment, string) (*manifest.Manifest, error)
	resolveManifestMutex       sync.RWMutex
	resolveManifestArgsForCall []struct {
		arg1 *v1alpha1.BOSHDeployment
		arg2 string
	}
	resolveManifestReturns struct {
		result1 *manifest.Manifest
		result2 error
	}
	resolveManifestReturnsOnCall map[int]struct {
		result1 *manifest.Manifest
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeResolver) ReadDesiredManifest(arg1 context.Context, arg2 string, arg3 string) (*manifest.Manifest, error) {
	fake.readDesiredManifestMutex.Lock()
	ret, specificReturn := fake.readDesiredManifestReturnsOnCall[len(fake.readDesiredManifestArgsForCall)]
	fake.readDesiredManifestArgsForCall = append(fake.readDesiredManifestArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	fake.recordInvocation("ReadDesiredManifest", []interface{}{arg1, arg2, arg3})
	fake.readDesiredManifestMutex.Unlock()
	if fake.ReadDesiredManifestStub != nil {
		return fake.ReadDesiredManifestStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.readDesiredManifestReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeResolver) ReadDesiredManifestCallCount() int {
	fake.readDesiredManifestMutex.RLock()
	defer fake.readDesiredManifestMutex.RUnlock()
	return len(fake.readDesiredManifestArgsForCall)
}

func (fake *FakeResolver) ReadDesiredManifestCalls(stub func(context.Context, string, string) (*manifest.Manifest, error)) {
	fake.readDesiredManifestMutex.Lock()
	defer fake.readDesiredManifestMutex.Unlock()
	fake.ReadDesiredManifestStub = stub
}

func (fake *FakeResolver) ReadDesiredManifestArgsForCall(i int) (context.Context, string, string) {
	fake.readDesiredManifestMutex.RLock()
	defer fake.readDesiredManifestMutex.RUnlock()
	argsForCall := fake.readDesiredManifestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeResolver) ReadDesiredManifestReturns(result1 *manifest.Manifest, result2 error) {
	fake.readDesiredManifestMutex.Lock()
	defer fake.readDesiredManifestMutex.Unlock()
	fake.ReadDesiredManifestStub = nil
	fake.readDesiredManifestReturns = struct {
		result1 *manifest.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakeResolver) ReadDesiredManifestReturnsOnCall(i int, result1 *manifest.Manifest, result2 error) {
	fake.readDesiredManifestMutex.Lock()
	defer fake.readDesiredManifestMutex.Unlock()
	fake.ReadDesiredManifestStub = nil
	if fake.readDesiredManifestReturnsOnCall == nil {
		fake.readDesiredManifestReturnsOnCall = make(map[int]struct {
			result1 *manifest.Manifest
			result2 error
		})
	}
	fake.readDesiredManifestReturnsOnCall[i] = struct {
		result1 *manifest.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakeResolver) ResolveManifest(arg1 *v1alpha1.BOSHDeployment, arg2 string) (*manifest.Manifest, error) {
	fake.resolveManifestMutex.Lock()
	ret, specificReturn := fake.resolveManifestReturnsOnCall[len(fake.resolveManifestArgsForCall)]
	fake.resolveManifestArgsForCall = append(fake.resolveManifestArgsForCall, struct {
		arg1 *v1alpha1.BOSHDeployment
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("ResolveManifest", []interface{}{arg1, arg2})
	fake.resolveManifestMutex.Unlock()
	if fake.ResolveManifestStub != nil {
		return fake.ResolveManifestStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.resolveManifestReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeResolver) ResolveManifestCallCount() int {
	fake.resolveManifestMutex.RLock()
	defer fake.resolveManifestMutex.RUnlock()
	return len(fake.resolveManifestArgsForCall)
}

func (fake *FakeResolver) ResolveManifestCalls(stub func(*v1alpha1.BOSHDeployment, string) (*manifest.Manifest, error)) {
	fake.resolveManifestMutex.Lock()
	defer fake.resolveManifestMutex.Unlock()
	fake.ResolveManifestStub = stub
}

func (fake *FakeResolver) ResolveManifestArgsForCall(i int) (*v1alpha1.BOSHDeployment, string) {
	fake.resolveManifestMutex.RLock()
	defer fake.resolveManifestMutex.RUnlock()
	argsForCall := fake.resolveManifestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeResolver) ResolveManifestReturns(result1 *manifest.Manifest, result2 error) {
	fake.resolveManifestMutex.Lock()
	defer fake.resolveManifestMutex.Unlock()
	fake.ResolveManifestStub = nil
	fake.resolveManifestReturns = struct {
		result1 *manifest.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakeResolver) ResolveManifestReturnsOnCall(i int, result1 *manifest.Manifest, result2 error) {
	fake.resolveManifestMutex.Lock()
	defer fake.resolveManifestMutex.Unlock()
	fake.ResolveManifestStub = nil
	if fake.resolveManifestReturnsOnCall == nil {
		fake.resolveManifestReturnsOnCall = make(map[int]struct {
			result1 *manifest.Manifest
			result2 error
		})
	}
	fake.resolveManifestReturnsOnCall[i] = struct {
		result1 *manifest.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakeResolver) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.readDesiredManifestMutex.RLock()
	defer fake.readDesiredManifestMutex.RUnlock()
	fake.resolveManifestMutex.RLock()
	defer fake.resolveManifestMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeResolver) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ manifest.Resolver = new(FakeResolver)
