// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	context "context"
	sync "sync"

	manifest "code.cloudfoundry.org/cf-operator/pkg/bosh/manifest"
	v1alpha1 "code.cloudfoundry.org/cf-operator/pkg/kube/apis/boshdeployment/v1alpha1"
	boshdeployment "code.cloudfoundry.org/cf-operator/pkg/kube/controllers/boshdeployment"
)

type FakeResolver struct {
	LatestVersionStub        func(context.Context, string, string) string
	latestVersionMutex       sync.RWMutex
	latestVersionArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	latestVersionReturns struct {
		result1 string
	}
	latestVersionReturnsOnCall map[int]struct {
		result1 string
	}
	ResolveManifestStub        func(*v1alpha1.BOSHDeployment, string) (*manifest.Manifest, error)
	resolveManifestMutex       sync.RWMutex
	resolveManifestArgsForCall []struct {
		arg1 *v1alpha1.BOSHDeployment
		arg2 string
	}
	resolveManifestReturns struct {
		result1 *manifest.Manifest
		result2 error
	}
	resolveManifestReturnsOnCall map[int]struct {
		result1 *manifest.Manifest
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeResolver) LatestVersion(arg1 context.Context, arg2 string, arg3 string) string {
	fake.latestVersionMutex.Lock()
	ret, specificReturn := fake.latestVersionReturnsOnCall[len(fake.latestVersionArgsForCall)]
	fake.latestVersionArgsForCall = append(fake.latestVersionArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	fake.recordInvocation("LatestVersion", []interface{}{arg1, arg2, arg3})
	fake.latestVersionMutex.Unlock()
	if fake.LatestVersionStub != nil {
		return fake.LatestVersionStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.latestVersionReturns
	return fakeReturns.result1
}

func (fake *FakeResolver) LatestVersionCallCount() int {
	fake.latestVersionMutex.RLock()
	defer fake.latestVersionMutex.RUnlock()
	return len(fake.latestVersionArgsForCall)
}

func (fake *FakeResolver) LatestVersionCalls(stub func(context.Context, string, string) string) {
	fake.latestVersionMutex.Lock()
	defer fake.latestVersionMutex.Unlock()
	fake.LatestVersionStub = stub
}

func (fake *FakeResolver) LatestVersionArgsForCall(i int) (context.Context, string, string) {
	fake.latestVersionMutex.RLock()
	defer fake.latestVersionMutex.RUnlock()
	argsForCall := fake.latestVersionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeResolver) LatestVersionReturns(result1 string) {
	fake.latestVersionMutex.Lock()
	defer fake.latestVersionMutex.Unlock()
	fake.LatestVersionStub = nil
	fake.latestVersionReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeResolver) LatestVersionReturnsOnCall(i int, result1 string) {
	fake.latestVersionMutex.Lock()
	defer fake.latestVersionMutex.Unlock()
	fake.LatestVersionStub = nil
	if fake.latestVersionReturnsOnCall == nil {
		fake.latestVersionReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.latestVersionReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeResolver) ResolveManifest(arg1 *v1alpha1.BOSHDeployment, arg2 string) (*manifest.Manifest, error) {
	fake.resolveManifestMutex.Lock()
	ret, specificReturn := fake.resolveManifestReturnsOnCall[len(fake.resolveManifestArgsForCall)]
	fake.resolveManifestArgsForCall = append(fake.resolveManifestArgsForCall, struct {
		arg1 *v1alpha1.BOSHDeployment
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("ResolveManifest", []interface{}{arg1, arg2})
	fake.resolveManifestMutex.Unlock()
	if fake.ResolveManifestStub != nil {
		return fake.ResolveManifestStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.resolveManifestReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeResolver) ResolveManifestCallCount() int {
	fake.resolveManifestMutex.RLock()
	defer fake.resolveManifestMutex.RUnlock()
	return len(fake.resolveManifestArgsForCall)
}

func (fake *FakeResolver) ResolveManifestCalls(stub func(*v1alpha1.BOSHDeployment, string) (*manifest.Manifest, error)) {
	fake.resolveManifestMutex.Lock()
	defer fake.resolveManifestMutex.Unlock()
	fake.ResolveManifestStub = stub
}

func (fake *FakeResolver) ResolveManifestArgsForCall(i int) (*v1alpha1.BOSHDeployment, string) {
	fake.resolveManifestMutex.RLock()
	defer fake.resolveManifestMutex.RUnlock()
	argsForCall := fake.resolveManifestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeResolver) ResolveManifestReturns(result1 *manifest.Manifest, result2 error) {
	fake.resolveManifestMutex.Lock()
	defer fake.resolveManifestMutex.Unlock()
	fake.ResolveManifestStub = nil
	fake.resolveManifestReturns = struct {
		result1 *manifest.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakeResolver) ResolveManifestReturnsOnCall(i int, result1 *manifest.Manifest, result2 error) {
	fake.resolveManifestMutex.Lock()
	defer fake.resolveManifestMutex.Unlock()
	fake.ResolveManifestStub = nil
	if fake.resolveManifestReturnsOnCall == nil {
		fake.resolveManifestReturnsOnCall = make(map[int]struct {
			result1 *manifest.Manifest
			result2 error
		})
	}
	fake.resolveManifestReturnsOnCall[i] = struct {
		result1 *manifest.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakeResolver) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.latestVersionMutex.RLock()
	defer fake.latestVersionMutex.RUnlock()
	fake.resolveManifestMutex.RLock()
	defer fake.resolveManifestMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeResolver) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ boshdeployment.Resolver = new(FakeResolver)
