/*

Don't alter this file, it was generated.

*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "code.cloudfoundry.org/cf-operator/pkg/kube/apis/quarksstatefulset/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeQuarksStatefulSets implements QuarksStatefulSetInterface
type FakeQuarksStatefulSets struct {
	Fake *FakeQuarksstatefulsetV1alpha1
	ns   string
}

var quarksstatefulsetsResource = schema.GroupVersionResource{Group: "quarksstatefulset", Version: "v1alpha1", Resource: "quarksstatefulsets"}

var quarksstatefulsetsKind = schema.GroupVersionKind{Group: "quarksstatefulset", Version: "v1alpha1", Kind: "QuarksStatefulSet"}

// Get takes name of the quarksStatefulSet, and returns the corresponding quarksStatefulSet object, and an error if there is any.
func (c *FakeQuarksStatefulSets) Get(name string, options v1.GetOptions) (result *v1alpha1.QuarksStatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(quarksstatefulsetsResource, c.ns, name), &v1alpha1.QuarksStatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QuarksStatefulSet), err
}

// List takes label and field selectors, and returns the list of QuarksStatefulSets that match those selectors.
func (c *FakeQuarksStatefulSets) List(opts v1.ListOptions) (result *v1alpha1.QuarksStatefulSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(quarksstatefulsetsResource, quarksstatefulsetsKind, c.ns, opts), &v1alpha1.QuarksStatefulSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.QuarksStatefulSetList{ListMeta: obj.(*v1alpha1.QuarksStatefulSetList).ListMeta}
	for _, item := range obj.(*v1alpha1.QuarksStatefulSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested quarksStatefulSets.
func (c *FakeQuarksStatefulSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(quarksstatefulsetsResource, c.ns, opts))

}

// Create takes the representation of a quarksStatefulSet and creates it.  Returns the server's representation of the quarksStatefulSet, and an error, if there is any.
func (c *FakeQuarksStatefulSets) Create(quarksStatefulSet *v1alpha1.QuarksStatefulSet) (result *v1alpha1.QuarksStatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(quarksstatefulsetsResource, c.ns, quarksStatefulSet), &v1alpha1.QuarksStatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QuarksStatefulSet), err
}

// Update takes the representation of a quarksStatefulSet and updates it. Returns the server's representation of the quarksStatefulSet, and an error, if there is any.
func (c *FakeQuarksStatefulSets) Update(quarksStatefulSet *v1alpha1.QuarksStatefulSet) (result *v1alpha1.QuarksStatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(quarksstatefulsetsResource, c.ns, quarksStatefulSet), &v1alpha1.QuarksStatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QuarksStatefulSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeQuarksStatefulSets) UpdateStatus(quarksStatefulSet *v1alpha1.QuarksStatefulSet) (*v1alpha1.QuarksStatefulSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(quarksstatefulsetsResource, "status", c.ns, quarksStatefulSet), &v1alpha1.QuarksStatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QuarksStatefulSet), err
}

// Delete takes name of the quarksStatefulSet and deletes it. Returns an error if one occurs.
func (c *FakeQuarksStatefulSets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(quarksstatefulsetsResource, c.ns, name), &v1alpha1.QuarksStatefulSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeQuarksStatefulSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(quarksstatefulsetsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.QuarksStatefulSetList{})
	return err
}

// Patch applies the patch and returns the patched quarksStatefulSet.
func (c *FakeQuarksStatefulSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.QuarksStatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(quarksstatefulsetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.QuarksStatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QuarksStatefulSet), err
}
