/*

Don't alter this file, it was generated.

*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "code.cloudfoundry.org/cf-operator/pkg/kube/apis/extendedsecret/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExtendedSecrets implements ExtendedSecretInterface
type FakeExtendedSecrets struct {
	Fake *FakeExtendedsecretV1alpha1
	ns   string
}

var extendedsecretsResource = schema.GroupVersionResource{Group: "extendedsecret", Version: "v1alpha1", Resource: "extendedsecrets"}

var extendedsecretsKind = schema.GroupVersionKind{Group: "extendedsecret", Version: "v1alpha1", Kind: "ExtendedSecret"}

// Get takes name of the extendedSecret, and returns the corresponding extendedSecret object, and an error if there is any.
func (c *FakeExtendedSecrets) Get(name string, options v1.GetOptions) (result *v1alpha1.ExtendedSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(extendedsecretsResource, c.ns, name), &v1alpha1.ExtendedSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendedSecret), err
}

// List takes label and field selectors, and returns the list of ExtendedSecrets that match those selectors.
func (c *FakeExtendedSecrets) List(opts v1.ListOptions) (result *v1alpha1.ExtendedSecretList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(extendedsecretsResource, extendedsecretsKind, c.ns, opts), &v1alpha1.ExtendedSecretList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ExtendedSecretList{ListMeta: obj.(*v1alpha1.ExtendedSecretList).ListMeta}
	for _, item := range obj.(*v1alpha1.ExtendedSecretList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested extendedSecrets.
func (c *FakeExtendedSecrets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(extendedsecretsResource, c.ns, opts))

}

// Create takes the representation of a extendedSecret and creates it.  Returns the server's representation of the extendedSecret, and an error, if there is any.
func (c *FakeExtendedSecrets) Create(extendedSecret *v1alpha1.ExtendedSecret) (result *v1alpha1.ExtendedSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(extendedsecretsResource, c.ns, extendedSecret), &v1alpha1.ExtendedSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendedSecret), err
}

// Update takes the representation of a extendedSecret and updates it. Returns the server's representation of the extendedSecret, and an error, if there is any.
func (c *FakeExtendedSecrets) Update(extendedSecret *v1alpha1.ExtendedSecret) (result *v1alpha1.ExtendedSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(extendedsecretsResource, c.ns, extendedSecret), &v1alpha1.ExtendedSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendedSecret), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeExtendedSecrets) UpdateStatus(extendedSecret *v1alpha1.ExtendedSecret) (*v1alpha1.ExtendedSecret, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(extendedsecretsResource, "status", c.ns, extendedSecret), &v1alpha1.ExtendedSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendedSecret), err
}

// Delete takes name of the extendedSecret and deletes it. Returns an error if one occurs.
func (c *FakeExtendedSecrets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(extendedsecretsResource, c.ns, name), &v1alpha1.ExtendedSecret{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExtendedSecrets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(extendedsecretsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ExtendedSecretList{})
	return err
}

// Patch applies the patch and returns the patched extendedSecret.
func (c *FakeExtendedSecrets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ExtendedSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(extendedsecretsResource, c.ns, name, data, subresources...), &v1alpha1.ExtendedSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendedSecret), err
}
